### ISSUE TITLE
Plan for code release

### ISSUE THREAD

**Issue by SiyuanYan1** [yeerwen/MedCoSS#1]
Congratulations on having your paper accepted to CVPR! When can we expect to access the complete code repository?

**Comment by yeerwen** [comment]
I am preparing the pre-training code and intend to make it open source within the next two days. The remaining code will be made available by the end of the next week.

**Comment by yeerwen** [comment]
Hi,

I apologize for not being able to release the rest of the code as promised at the end of last week. Unfortunately, I was taken ill with the flu, which has caused some delays. I may need another two or three days to check the preprocessing and fine-tuning code before it's ready for release.

Thank you for your understanding and patience.
