### ISSUE TITLE
3D-CT-Kmeans问题

### ISSUE THREAD

**Issue by WYL211** [yeerwen/MedCoSS#10]
您好，我想请问一下在跑3D-CT的kmeans时，DeepLesion_dataset.py这个文件需要用到SSL_data_deeplesion.txt这个文本文件，但是我找了DeepLesion数据下载的地方，没有找到这个文本文件，我也去查找了有关CT数据处理的文件，这个文件没发现是通过预处理生成的，请问您是怎么得到这个文件，谢谢您的解答。
![微信图片_20241008191556](https://github.com/user-attachments/assets/478098a1-2e49-4a98-a78d-bb43331718c8)

**Comment by yeerwen** [comment]
您好， https://github.com/yeerwen/MedCoSS/blob/main/Preprocess/splitting_to_patches.py 这里有开源如何生成该文件。
