### ISSUE TITLE
Maximum epoch for other baselines?

### ISSUE THREAD

**Issue by SiyuanYan1** [yeerwen/MedCoSS#4]
For the MedCoSS pretraining, the maximum epoch is set to 300 epochs for each of the 5 modalities, totaling 1,500 epochs. In contrast, for the single-modal baselines and two variants of joint SSL, how do you set the maximum epoch? Can you provide these details? Many thanks!

**Comment by yeerwen** [comment]
Single-modal baselines:  300 epochs.
Joint SSL baselines: 300 epochs. (Note that all data across the five modalities will be processed during each epoch.)
