### ISSUE TITLE
数据数量

### ISSUE THREAD

**Issue by hrcsu** [yeerwen/MedCoSS#7]
作者您好，请问ADNI数据集和TCGA数据集纳入的原始数据数量分别是多少呢

**Comment by yeerwen** [comment]
您好，ADNI是在官网上通过筛选得到的，TCGA的原始数据就是用的给出的7个数据集，然后从中进行筛选。具体操作可以看我们的appendix.

**Comment by hrcsu** [comment]
方便告知一下具体筛出来的数量吗？补充材料里边这俩个数据集好像没有具体的数量

**Comment by yeerwen** [comment]
ADNI是官方的数据集筛选的，官方数据集多大我也不知道，里面数据挺杂的。TCGA我们共从2181个患者的WSI中，先切成了 6444267个patch，然后从中筛选的本篇论文中使用的子数据集。
