### ISSUE TITLE
预训练report

### ISSUE THREAD

**Issue by WYL211** [yeerwen/MedCoSS#9]
您好，我想请问一下预训练report时，我处理了report的csv文件得到了master.csv文件，并且对他的预训练权重也跑了出来，但在进行report的kmeans的时候，出现了断言错误，由于MIMIC-CXR-JPG的文件太大，我只下载了p10的数据，这个数据的存放路径已经是怎样的呢，        for itr in tqdm.tqdm(range(num_clusters)):
            top_k_name = top_k_samples_name[itr]
            print(top_k_name)
            top_k_name = [spare_name.replace("/data4t/wushangqian/Pretrained_dataset/1D/2019.MIMIC-CXR-JPG/2.0.0/", "") for
                          spare_name in top_k_name]  # Need to modify
            filtered_df = df[df['Path'].isin(top_k_name)]
            print("len(top_k_name)2: ", len(top_k_name))
            print("len(filtered_df)2: ", len(filtered_df))
            assert len(top_k_name) == len(filtered_df)
            write_header = not pd.io.common.file_exists(os.path.join(save_path, file_path))
            filtered_df.to_csv(os.path.join(save_path, file_path), index=False, mode='a', header=write_header)
上面路径是我仿照您的路径来设置我的路径，但发现您的路径没有到2.0.0这一层，那请问p10的数据是应该怎样的一个层级安排呢？
再有就是下面这个断言错误，
![b53189a70e3b17592b5132df2643b28](https://github.com/user-attachments/assets/647eece8-0f7d-4f61-a127-0bb6ebefebfa)
如图片中所说，请问kmean这一步是怎样处理的呢，去除path文件路径的前缀，那应该去除到哪一层级呢，期待您的答复。

**Comment by yeerwen** [comment]
您好，这是我数据的存储：
![QQ_1728006114337](https://github.com/user-attachments/assets/ad0ffcc0-3ed2-4720-b4a2-24dc7251724d)
从报错来看，似乎是聚类点的筛选出了问题，可以把df['Path']和top_k_name的路径打印出来看看前缀是否有不一致的地方。
